import { ChainKey } from "./enums.js";

export type ChainVm =
  | "evm"
  | "near"
  | "cardano"
  | "solana"
  | "tron"
  | "sui"
  | "ton"
  | "aptos"
  | "hypercore"
  | "bitcoin"
  | "xrpl"
  | "stellar"
  | "cosmos"
  | "starknet";

export type ChainDefinition = {
  key: (typeof ChainKey)[keyof typeof ChainKey];
  name: string;
  short: string;
  chainId: number;
  eid: number;
  endpoint: `0x${string}`;
  explorer: string;
  rpc: string;
  nativeSymbol: string;
  enabled: boolean;
  testnet: boolean;
  evm: boolean;
  vm: ChainVm;
  featured: boolean;
};

/** LayerZero EndpointV2 is shared across these testnets. */
const LZ_TESTNET_ENDPOINT = "0x6EDCE65403992e310A62460808c4b910D972f10f" as const;
const LZ_MAINNET_ENDPOINT = "0x1a44076050125825900e736c501f859c50fE728c" as const;
const ZERO = "0x0000000000000000000000000000000000000000" as const;

function evmChain(
  partial: Omit<ChainDefinition, "evm" | "vm">,
): ChainDefinition {
  return { ...partial, evm: true, vm: "evm" };
}

export const CHAINS: Record<(typeof ChainKey)[keyof typeof ChainKey], ChainDefinition> = {
  [ChainKey.Ethereum]: evmChain({
    key: ChainKey.Ethereum,
    name: "Ethereum",
    short: "ETH",
    chainId: 1,
    eid: 30101,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://etherscan.io",
    rpc: "https://ethereum-rpc.publicnode.com",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Base]: evmChain({
    key: ChainKey.Base,
    name: "Base",
    short: "Base",
    chainId: 8453,
    eid: 30184,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://basescan.org",
    rpc: "https://mainnet.base.org",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Arbitrum]: evmChain({
    key: ChainKey.Arbitrum,
    name: "Arbitrum One",
    short: "Arb",
    chainId: 42161,
    eid: 30110,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://arbiscan.io",
    rpc: "https://arb1.arbitrum.io/rpc",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Optimism]: evmChain({
    key: ChainKey.Optimism,
    name: "Optimism",
    short: "OP",
    chainId: 10,
    eid: 30111,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://optimistic.etherscan.io",
    rpc: "https://mainnet.optimism.io",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Bnb]: evmChain({
    key: ChainKey.Bnb,
    name: "BNB Chain",
    short: "BNB",
    chainId: 56,
    eid: 30102,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://bscscan.com",
    rpc: "https://bsc-dataseed.binance.org",
    nativeSymbol: "BNB",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.BaseSepolia]: evmChain({
    key: ChainKey.BaseSepolia,
    name: "Base Sepolia",
    short: "BaseSep",
    chainId: 84532,
    eid: 40245,
    endpoint: LZ_TESTNET_ENDPOINT,
    explorer: "https://sepolia.basescan.org",
    rpc: "https://sepolia.base.org",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: true,
    featured: false,
  }),
  [ChainKey.ArbSepolia]: evmChain({
    key: ChainKey.ArbSepolia,
    name: "Arbitrum Sepolia",
    short: "ArbSep",
    chainId: 421614,
    eid: 40231,
    endpoint: LZ_TESTNET_ENDPOINT,
    explorer: "https://sepolia.arbiscan.io",
    rpc: "https://sepolia-rollup.arbitrum.io/rpc",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: true,
    featured: false,
  }),
  [ChainKey.Avalanche]: evmChain({
    key: ChainKey.Avalanche,
    name: "Avalanche",
    short: "AVAX",
    chainId: 43114,
    eid: 30106,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://snowtrace.io",
    rpc: "https://api.avax.network/ext/bc/C/rpc",
    nativeSymbol: "AVAX",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Cardano]: {
    key: ChainKey.Cardano,
    name: "Cardano",
    short: "ADA",
    /** BIP44 coin type. Not an EVM chain id. */
    chainId: 1815,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://cardanoscan.io",
    rpc: "https://api.koios.rest/api/v1",
    nativeSymbol: "ADA",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "cardano",
    featured: true,
  },
  [ChainKey.Near]: {
    key: ChainKey.Near,
    name: "NEAR",
    short: "NEAR",
    /** CAIP / WalletConnect numeric id for NEAR mainnet. Not Aurora. */
    chainId: 397,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://nearblocks.io",
    rpc: "https://rpc.mainnet.near.org",
    nativeSymbol: "NEAR",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "near",
    featured: true,
  },
  [ChainKey.EthereumSepolia]: evmChain({
    key: ChainKey.EthereumSepolia,
    name: "Ethereum Sepolia",
    short: "ETHSep",
    chainId: 11155111,
    eid: 40161,
    endpoint: LZ_TESTNET_ENDPOINT,
    explorer: "https://sepolia.etherscan.io",
    rpc: "https://ethereum-sepolia-rpc.publicnode.com",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: true,
    featured: false,
  }),
  [ChainKey.AvalancheFuji]: evmChain({
    key: ChainKey.AvalancheFuji,
    name: "Avalanche Fuji",
    short: "Fuji",
    chainId: 43113,
    eid: 40106,
    endpoint: LZ_TESTNET_ENDPOINT,
    explorer: "https://testnet.snowtrace.io",
    rpc: "https://api.avax-test.network/ext/bc/C/rpc",
    nativeSymbol: "AVAX",
    enabled: true,
    testnet: true,
    featured: false,
  }),
  [ChainKey.BnbTestnet]: evmChain({
    key: ChainKey.BnbTestnet,
    name: "BNB Testnet",
    short: "BNBTest",
    chainId: 97,
    eid: 40102,
    endpoint: LZ_TESTNET_ENDPOINT,
    explorer: "https://testnet.bscscan.com",
    rpc: "https://bsc-testnet-rpc.publicnode.com",
    nativeSymbol: "BNB",
    enabled: true,
    testnet: true,
    featured: false,
  }),
  [ChainKey.CardanoPreprod]: {
    key: ChainKey.CardanoPreprod,
    name: "Cardano Preprod",
    short: "ADAPre",
    chainId: 18151,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://preprod.cardanoscan.io",
    rpc: "https://preprod.koios.rest/api/v1",
    nativeSymbol: "ADA",
    enabled: true,
    testnet: true,
    evm: false,
    vm: "cardano",
    featured: false,
  },
  [ChainKey.NearTestnet]: {
    key: ChainKey.NearTestnet,
    name: "NEAR Testnet",
    short: "NEARTest",
    chainId: 398,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://testnet.nearblocks.io",
    rpc: "https://rpc.testnet.near.org",
    nativeSymbol: "NEAR",
    enabled: true,
    testnet: true,
    evm: false,
    vm: "near",
    featured: false,
  },
  [ChainKey.Solana]: {
    key: ChainKey.Solana,
    name: "Solana",
    short: "SOL",
    /** Solana mainnet-beta cluster id. Not an EVM chain id. */
    chainId: 101,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://solscan.io",
    rpc: "https://api.mainnet-beta.solana.com",
    nativeSymbol: "SOL",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "solana",
    featured: true,
  },
  [ChainKey.SolanaDevnet]: {
    key: ChainKey.SolanaDevnet,
    name: "Solana Devnet",
    short: "SOLDev",
    chainId: 103,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://solscan.io/?cluster=devnet",
    rpc: "https://api.devnet.solana.com",
    nativeSymbol: "SOL",
    enabled: true,
    testnet: true,
    evm: false,
    vm: "solana",
    featured: false,
  },
  [ChainKey.Polygon]: evmChain({
    key: ChainKey.Polygon,
    name: "Polygon",
    short: "POL",
    chainId: 137,
    eid: 30109,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://polygonscan.com",
    rpc: "https://polygon-bor-rpc.publicnode.com",
    nativeSymbol: "POL",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Fantom]: evmChain({
    key: ChainKey.Fantom,
    name: "Fantom",
    short: "FTM",
    chainId: 250,
    eid: 30112,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://ftmscan.com",
    rpc: "https://fantom-rpc.publicnode.com",
    nativeSymbol: "FTM",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Mantle]: evmChain({
    key: ChainKey.Mantle,
    name: "Mantle",
    short: "MNT",
    chainId: 5000,
    eid: 30181,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://mantlescan.xyz",
    rpc: "https://rpc.mantle.xyz",
    nativeSymbol: "MNT",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.WorldChain]: evmChain({
    key: ChainKey.WorldChain,
    name: "World Chain",
    short: "World",
    chainId: 480,
    eid: 30319,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://worldscan.org",
    rpc: "https://worldchain.drpc.org",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.HyperEvm]: evmChain({
    key: ChainKey.HyperEvm,
    name: "HyperEVM",
    short: "HyperEVM",
    chainId: 999,
    eid: 30367,
    endpoint: "0x3A73033C0b1407574C76BdBAc67f126f6b4a9AA9",
    explorer: "https://hyperevmscan.io",
    rpc: "https://rpc.hyperliquid.xyz/evm",
    nativeSymbol: "HYPE",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Tron]: {
    key: ChainKey.Tron,
    name: "Tron",
    short: "TRX",
    chainId: 728126428,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://tronscan.org",
    rpc: "https://api.trongrid.io",
    nativeSymbol: "TRX",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "tron",
    featured: true,
  },
  [ChainKey.Sui]: {
    key: ChainKey.Sui,
    name: "Sui",
    short: "SUI",
    chainId: 784,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://suiscan.xyz",
    rpc: "https://fullnode.mainnet.sui.io:443",
    nativeSymbol: "SUI",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "sui",
    featured: true,
  },
  [ChainKey.Ton]: {
    key: ChainKey.Ton,
    name: "TON",
    short: "TON",
    chainId: 607,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://tonviewer.com",
    rpc: "https://toncenter.com/api/v2/jsonRPC",
    nativeSymbol: "TON",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "ton",
    featured: true,
  },
  [ChainKey.HyperCore]: {
    key: ChainKey.HyperCore,
    name: "HyperCore",
    short: "HyperCore",
    chainId: 998,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://app.hyperliquid.xyz",
    rpc: "https://api.hyperliquid.xyz/info",
    nativeSymbol: "HYPE",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "hypercore",
    featured: true,
  },
  [ChainKey.Aptos]: {
    key: ChainKey.Aptos,
    name: "Aptos",
    short: "APT",
    chainId: 637,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://explorer.aptoslabs.com",
    rpc: "https://fullnode.mainnet.aptoslabs.com/v1",
    nativeSymbol: "APT",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "aptos",
    featured: true,
  },
  [ChainKey.Monad]: evmChain({
    key: ChainKey.Monad,
    name: "Monad",
    short: "MON",
    chainId: 143,
    eid: 30390,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://monadscan.com",
    rpc: "https://rpc.monad.xyz",
    nativeSymbol: "MON",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Plasma]: evmChain({
    key: ChainKey.Plasma,
    name: "Plasma",
    short: "XPL",
    chainId: 9745,
    eid: 30383,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://plasmascan.to",
    rpc: "https://rpc.plasma.to",
    nativeSymbol: "XPL",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Gnosis]: evmChain({
    key: ChainKey.Gnosis,
    name: "Gnosis",
    short: "GNO",
    chainId: 100,
    eid: 30145,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://gnosisscan.io",
    rpc: "https://rpc.gnosischain.com",
    nativeSymbol: "xDAI",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Cronos]: evmChain({
    key: ChainKey.Cronos,
    name: "Cronos",
    short: "CRO",
    chainId: 25,
    eid: 30359,
    endpoint: "0x3A73033C0b1407574C76BdBAc67f126f6b4a9AA9",
    explorer: "https://cronoscan.com",
    rpc: "https://evm.cronos.org",
    nativeSymbol: "CRO",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Sei]: evmChain({
    key: ChainKey.Sei,
    name: "Sei",
    short: "SEI",
    chainId: 1329,
    eid: 30280,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://seitrace.com",
    rpc: "https://evm-rpc.sei-apis.com",
    nativeSymbol: "SEI",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Sonic]: evmChain({
    key: ChainKey.Sonic,
    name: "Sonic",
    short: "S",
    chainId: 146,
    eid: 30332,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://sonicscan.org",
    rpc: "https://rpc.soniclabs.com",
    nativeSymbol: "S",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Berachain]: evmChain({
    key: ChainKey.Berachain,
    name: "Berachain",
    short: "BERA",
    chainId: 80094,
    eid: 30362,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://berascan.com",
    rpc: "https://rpc.berachain.com",
    nativeSymbol: "BERA",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Ronin]: evmChain({
    key: ChainKey.Ronin,
    name: "Ronin",
    short: "RON",
    chainId: 2020,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://app.roninchain.com",
    rpc: "https://api.roninchain.com/rpc",
    nativeSymbol: "RON",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Xdc]: evmChain({
    key: ChainKey.Xdc,
    name: "XDC",
    short: "XDC",
    chainId: 50,
    eid: 30365,
    endpoint: "0xcb566e3B6934Fa77258d68ea18E931fa75e1aaAa",
    explorer: "https://xdcscan.com",
    rpc: "https://rpc.xdc.org",
    nativeSymbol: "XDC",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Viction]: evmChain({
    key: ChainKey.Viction,
    name: "Viction",
    short: "VIC",
    chainId: 88,
    eid: 30196,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://www.vicscan.xyz",
    rpc: "https://rpc.viction.xyz",
    nativeSymbol: "VIC",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Iotex]: evmChain({
    key: ChainKey.Iotex,
    name: "IoTeX",
    short: "IOTX",
    chainId: 4689,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://iotexscan.io",
    rpc: "https://babel-api.mainnet.iotex.io",
    nativeSymbol: "IOTX",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Kaia]: evmChain({
    key: ChainKey.Kaia,
    name: "Kaia",
    short: "KAIA",
    chainId: 8217,
    eid: 30150,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://kaiascan.io",
    rpc: "https://public-en.node.kaia.io",
    nativeSymbol: "KAIA",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.InjectiveEvm]: evmChain({
    key: ChainKey.InjectiveEvm,
    name: "Injective EVM",
    short: "INJ",
    chainId: 1776,
    eid: 30394,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://blockscout.injective.network",
    rpc: "https://sentry.evm-rpc.injective.network",
    nativeSymbol: "INJ",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Tempo]: evmChain({
    key: ChainKey.Tempo,
    name: "Tempo",
    short: "Tempo",
    chainId: 4217,
    eid: 30410,
    endpoint: "0x20bb7c2e2f4e5Ca2b4C57060d1ae2615245dCC9c",
    explorer: "https://explore.tempo.xyz",
    rpc: "https://rpc.tempo.xyz",
    nativeSymbol: "USD",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.FlowEvm]: evmChain({
    key: ChainKey.FlowEvm,
    name: "Flow EVM",
    short: "FLOW",
    chainId: 747,
    eid: 30336,
    endpoint: "0xcb566e3B6934Fa77258d68ea18E931fa75e1aaAa",
    explorer: "https://evm.flowscan.io",
    rpc: "https://mainnet.evm.nodes.onflow.org",
    nativeSymbol: "FLOW",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Core]: evmChain({
    key: ChainKey.Core,
    name: "Core",
    short: "CORE",
    chainId: 1116,
    eid: 30153,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://scan.coredao.org",
    rpc: "https://rpc.coredao.org",
    nativeSymbol: "CORE",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Flare]: evmChain({
    key: ChainKey.Flare,
    name: "Flare",
    short: "FLR",
    chainId: 14,
    eid: 30295,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://flarescan.com",
    rpc: "https://flare-api.flare.network/ext/C/rpc",
    nativeSymbol: "FLR",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Celo]: evmChain({
    key: ChainKey.Celo,
    name: "Celo",
    short: "CELO",
    chainId: 42220,
    eid: 30125,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://celoscan.io",
    rpc: "https://forno.celo.org",
    nativeSymbol: "CELO",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.OpBnb]: evmChain({
    key: ChainKey.OpBnb,
    name: "opBNB",
    short: "opBNB",
    chainId: 204,
    eid: 30202,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://opbnbscan.com",
    rpc: "https://opbnb-mainnet-rpc.bnbchain.org",
    nativeSymbol: "BNB",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Unichain]: evmChain({
    key: ChainKey.Unichain,
    name: "Unichain",
    short: "UNI",
    chainId: 130,
    eid: 30320,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://uniscan.xyz",
    rpc: "https://mainnet.unichain.org",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Linea]: evmChain({
    key: ChainKey.Linea,
    name: "Linea",
    short: "Linea",
    chainId: 59144,
    eid: 30183,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://lineascan.build",
    rpc: "https://rpc.linea.build",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Scroll]: evmChain({
    key: ChainKey.Scroll,
    name: "Scroll",
    short: "SCR",
    chainId: 534352,
    eid: 30214,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://scrollscan.com",
    rpc: "https://rpc.scroll.io",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.ZkSync]: evmChain({
    key: ChainKey.ZkSync,
    name: "zkSync Era",
    short: "zkSync",
    chainId: 324,
    eid: 30165,
    endpoint: "0xD07C30aF3Ff30D96BDc9c6044958230Eb797DdbF",
    explorer: "https://era.zksync.network",
    rpc: "https://mainnet.era.zksync.io",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Blast]: evmChain({
    key: ChainKey.Blast,
    name: "Blast",
    short: "Blast",
    chainId: 81457,
    eid: 30243,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://blastscan.io",
    rpc: "https://rpc.blast.io",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Ink]: evmChain({
    key: ChainKey.Ink,
    name: "Ink",
    short: "Ink",
    chainId: 57073,
    eid: 30339,
    endpoint: "0xCa29f3A6f966Cb2fc0dE625F8f325c0C46dBe958",
    explorer: "https://explorer.inkonchain.com",
    rpc: "https://rpc-gel.inkonchain.com",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Soneium]: evmChain({
    key: ChainKey.Soneium,
    name: "Soneium",
    short: "Soneium",
    chainId: 1868,
    eid: 30340,
    endpoint: "0x4BcB6A963a9563C33569D7A512D35754221F3A19",
    explorer: "https://soneium.blockscout.com",
    rpc: "https://rpc.soneium.org",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.MegaEth]: evmChain({
    key: ChainKey.MegaEth,
    name: "MegaETH",
    short: "MegaETH",
    chainId: 4326,
    eid: 30398,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://mega.etherscan.io",
    rpc: "https://mainnet.megaeth.com/rpc",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.XLayer]: evmChain({
    key: ChainKey.XLayer,
    name: "X Layer",
    short: "XLayer",
    chainId: 196,
    eid: 30274,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://www.okx.com/web3/explorer/xlayer",
    rpc: "https://rpc.xlayer.tech",
    nativeSymbol: "OKB",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Gravity]: evmChain({
    key: ChainKey.Gravity,
    name: "Gravity",
    short: "G",
    chainId: 1625,
    eid: 30294,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://explorer.gravity.xyz",
    rpc: "https://rpc.gravity.xyz",
    nativeSymbol: "G",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Katana]: evmChain({
    key: ChainKey.Katana,
    name: "Katana",
    short: "Katana",
    chainId: 747474,
    eid: 30375,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://katanascan.com",
    rpc: "https://rpc.katana.network",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Abstract]: evmChain({
    key: ChainKey.Abstract,
    name: "Abstract",
    short: "ABS",
    chainId: 2741,
    eid: 30324,
    endpoint: "0x5c6cfF4b7C49805F8295Ff73C204ac83f3bC4AE7",
    explorer: "https://abscan.org",
    rpc: "https://api.mainnet.abs.xyz",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Manta]: evmChain({
    key: ChainKey.Manta,
    name: "Manta",
    short: "Manta",
    chainId: 169,
    eid: 30217,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://pacific-explorer.manta.network",
    rpc: "https://pacific-rpc.manta.network/http",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Metis]: evmChain({
    key: ChainKey.Metis,
    name: "Metis",
    short: "Metis",
    chainId: 1088,
    eid: 30151,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://andromeda-explorer.metis.io",
    rpc: "https://andromeda.metis.io/?owner=1088",
    nativeSymbol: "METIS",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Taiko]: evmChain({
    key: ChainKey.Taiko,
    name: "Taiko",
    short: "Taiko",
    chainId: 167000,
    eid: 30290,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://taikoscan.io",
    rpc: "https://rpc.mainnet.taiko.xyz",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.ImmutableZkEvm]: evmChain({
    key: ChainKey.ImmutableZkEvm,
    name: "Immutable zkEVM",
    short: "IMX",
    chainId: 13371,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://explorer.immutable.com",
    rpc: "https://rpc.immutable.com",
    nativeSymbol: "IMX",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Bob]: evmChain({
    key: ChainKey.Bob,
    name: "BOB",
    short: "BOB",
    chainId: 60808,
    eid: 30279,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://explorer.gobob.xyz",
    rpc: "https://rpc.gobob.xyz",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Morph]: evmChain({
    key: ChainKey.Morph,
    name: "Morph",
    short: "Morph",
    chainId: 2818,
    eid: 30322,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://explorer.morphl2.io",
    rpc: "https://rpc.morphl2.io",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Plume]: evmChain({
    key: ChainKey.Plume,
    name: "Plume",
    short: "PLUME",
    chainId: 98866,
    eid: 30370,
    endpoint: "0xC1b15d3B262BEeC0e3565C11C9e0F6134BdaCB36",
    explorer: "https://explorer.plume.org",
    rpc: "https://rpc.plume.org",
    nativeSymbol: "PLUME",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.ApeChain]: evmChain({
    key: ChainKey.ApeChain,
    name: "ApeChain",
    short: "APE",
    chainId: 33139,
    eid: 30312,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://apescan.io",
    rpc: "https://rpc.apechain.com",
    nativeSymbol: "APE",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Mode]: evmChain({
    key: ChainKey.Mode,
    name: "Mode",
    short: "Mode",
    chainId: 34443,
    eid: 30260,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://explorer.mode.network",
    rpc: "https://mainnet.mode.network",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Fraxtal]: evmChain({
    key: ChainKey.Fraxtal,
    name: "Fraxtal",
    short: "Fraxtal",
    chainId: 252,
    eid: 30255,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://fraxscan.com",
    rpc: "https://rpc.frax.com",
    nativeSymbol: "frxETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Boba]: evmChain({
    key: ChainKey.Boba,
    name: "Boba",
    short: "Boba",
    chainId: 288,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://bobascan.com",
    rpc: "https://mainnet.boba.network",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Lisk]: evmChain({
    key: ChainKey.Lisk,
    name: "Lisk",
    short: "Lisk",
    chainId: 1135,
    eid: 30321,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://blockscout.lisk.com",
    rpc: "https://rpc.api.lisk.com",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Zora]: evmChain({
    key: ChainKey.Zora,
    name: "Zora",
    short: "Zora",
    chainId: 7777777,
    eid: 30195,
    endpoint: LZ_MAINNET_ENDPOINT,
    explorer: "https://explorer.zora.energy",
    rpc: "https://rpc.zora.energy",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Robinhood]: evmChain({
    key: ChainKey.Robinhood,
    name: "Robinhood Chain",
    short: "RH",
    chainId: 4663,
    eid: 30416,
    endpoint: "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B",
    explorer: "https://robinhoodchain.blockscout.com",
    rpc: "https://rpc.mainnet.chain.robinhood.com",
    nativeSymbol: "ETH",
    enabled: true,
    testnet: false,
    featured: true,
  }),
  [ChainKey.Bitcoin]: {
    key: ChainKey.Bitcoin,
    name: "Bitcoin",
    short: "BTC",
    chainId: 833,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://mempool.space",
    rpc: "https://mempool.space/api",
    nativeSymbol: "BTC",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "bitcoin",
    featured: true,
  },
  [ChainKey.Xrpl]: {
    key: ChainKey.Xrpl,
    name: "XRP Ledger",
    short: "XRP",
    chainId: 144,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://livenet.xrpl.org",
    rpc: "https://xrplcluster.com",
    nativeSymbol: "XRP",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "xrpl",
    featured: true,
  },
  [ChainKey.Stellar]: {
    key: ChainKey.Stellar,
    name: "Stellar",
    short: "XLM",
    chainId: 148,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://stellar.expert/explorer/public",
    rpc: "https://horizon.stellar.org",
    nativeSymbol: "XLM",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "stellar",
    featured: true,
  },
  [ChainKey.Cosmos]: {
    key: ChainKey.Cosmos,
    name: "Cosmos Hub",
    short: "ATOM",
    chainId: 118,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://www.mintscan.io/cosmos",
    rpc: "https://rest.cosmos.directory/cosmoshub",
    nativeSymbol: "ATOM",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "cosmos",
    featured: true,
  },
  [ChainKey.Osmosis]: {
    key: ChainKey.Osmosis,
    name: "Osmosis",
    short: "OSMO",
    chainId: 100001,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://www.mintscan.io/osmosis",
    rpc: "https://rest.cosmos.directory/osmosis",
    nativeSymbol: "OSMO",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "cosmos",
    featured: true,
  },
  [ChainKey.Celestia]: {
    key: ChainKey.Celestia,
    name: "Celestia",
    short: "TIA",
    chainId: 100002,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://www.mintscan.io/celestia",
    rpc: "https://rest.cosmos.directory/celestia",
    nativeSymbol: "TIA",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "cosmos",
    featured: true,
  },
  [ChainKey.Starknet]: {
    key: ChainKey.Starknet,
    name: "Starknet",
    short: "STRK",
    chainId: 100003,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://starkscan.co",
    rpc: "https://starknet-mainnet.public.blastapi.io",
    nativeSymbol: "STRK",
    enabled: true,
    testnet: false,
    evm: false,
    vm: "starknet",
    featured: true,
  },
  [ChainKey.Filecoin]: evmChain({
    key: ChainKey.Filecoin,
    name: "Filecoin",
    short: "FIL",
    chainId: 314,
    eid: 0,
    endpoint: ZERO,
    explorer: "https://filfox.info/en",
    rpc: "https://api.node.glif.io/rpc/v1",
    nativeSymbol: "FIL",
    enabled: true,
    testnet: false,
    featured: true,
  }),
};

/** Product bar + holdings chains people actually use. Settings “mainstream” preset. */
const CORE_HOLDINGS_ORDER: Array<(typeof ChainKey)[keyof typeof ChainKey]> = [
  ChainKey.Ethereum,
  ChainKey.Avalanche,
  ChainKey.Base,
  ChainKey.Arbitrum,
  ChainKey.Cardano,
  ChainKey.Near,
  ChainKey.Bnb,
  ChainKey.Solana,
  ChainKey.Tron,
  ChainKey.Polygon,
  ChainKey.Sui,
  ChainKey.Ton,
  ChainKey.Aptos,
  ChainKey.Optimism,
];

/** Product bar: ETH · AVAX · Base · Arb · ADA · NEAR · BNB · SOL, then the extra holdings chains. */
const FEATURED_ORDER: Array<(typeof ChainKey)[keyof typeof ChainKey]> = [
  ChainKey.Ethereum,
  ChainKey.Avalanche,
  ChainKey.Base,
  ChainKey.Arbitrum,
  ChainKey.Cardano,
  ChainKey.Near,
  ChainKey.Bnb,
  ChainKey.Solana,
  ChainKey.Tron,
  ChainKey.Polygon,
  ChainKey.Sui,
  ChainKey.Ton,
  ChainKey.HyperCore,
  ChainKey.Aptos,
  ChainKey.HyperEvm,
  ChainKey.Fantom,
  ChainKey.Optimism,
  ChainKey.WorldChain,
  ChainKey.Mantle,
  ChainKey.Monad,
  ChainKey.Plasma,
  ChainKey.Gnosis,
  ChainKey.Cronos,
  ChainKey.Sei,
  ChainKey.Sonic,
  ChainKey.Berachain,
  ChainKey.Ronin,
  ChainKey.Xdc,
  ChainKey.Viction,
  ChainKey.Iotex,
  ChainKey.Kaia,
  ChainKey.InjectiveEvm,
  ChainKey.Tempo,
  ChainKey.FlowEvm,
  ChainKey.Core,
  ChainKey.Flare,
  ChainKey.Celo,
  ChainKey.OpBnb,
  ChainKey.Unichain,
  ChainKey.Linea,
  ChainKey.Scroll,
  ChainKey.ZkSync,
  ChainKey.Blast,
  ChainKey.Ink,
  ChainKey.Soneium,
  ChainKey.MegaEth,
  ChainKey.XLayer,
  ChainKey.Gravity,
  ChainKey.Katana,
  ChainKey.Abstract,
  ChainKey.Manta,
  ChainKey.Metis,
  ChainKey.Taiko,
  ChainKey.ImmutableZkEvm,
  ChainKey.Bob,
  ChainKey.Morph,
  ChainKey.Plume,
  ChainKey.ApeChain,
  ChainKey.Mode,
  ChainKey.Fraxtal,
  ChainKey.Boba,
  ChainKey.Lisk,
  ChainKey.Zora,
  ChainKey.Robinhood,
  ChainKey.Bitcoin,
  ChainKey.Xrpl,
  ChainKey.Stellar,
  ChainKey.Cosmos,
  ChainKey.Osmosis,
  ChainKey.Celestia,
  ChainKey.Starknet,
  ChainKey.Filecoin,
];

/** Wizard mint targets. Holdings-only EVM stay off this list. */
const ISSUANCE_ORDER: Array<(typeof ChainKey)[keyof typeof ChainKey]> = [
  ChainKey.Ethereum,
  ChainKey.Avalanche,
  ChainKey.Base,
  ChainKey.Arbitrum,
  ChainKey.Cardano,
  ChainKey.Near,
  ChainKey.Bnb,
  ChainKey.Solana,
  ChainKey.Polygon,
  ChainKey.Sui,
  ChainKey.Aptos,
  ChainKey.HyperEvm,
  ChainKey.Fantom,
  ChainKey.Optimism,
  ChainKey.WorldChain,
  ChainKey.Mantle,
  ChainKey.Monad,
  ChainKey.Plasma,
  ChainKey.Linea,
  ChainKey.Scroll,
  ChainKey.ZkSync,
  ChainKey.OpBnb,
  ChainKey.Unichain,
  ChainKey.Celo,
  ChainKey.Blast,
  ChainKey.Sei,
  ChainKey.Sonic,
  ChainKey.Gnosis,
  ChainKey.Ink,
  ChainKey.Soneium,
  ChainKey.MegaEth,
  ChainKey.Cronos,
  ChainKey.Ronin,
  ChainKey.XLayer,
  ChainKey.Abstract,
];

export function chainByChainId(chainId: number): ChainDefinition | undefined {
  return Object.values(CHAINS).find((c) => c.chainId === chainId && c.evm);
}

export function enabledChains(): ChainDefinition[] {
  return Object.values(CHAINS).filter((c) => c.enabled);
}

export function evmEnabledChains(): ChainDefinition[] {
  return Object.values(CHAINS).filter((c) => c.enabled && c.evm);
}

export function nativeChains(): ChainDefinition[] {
  return Object.values(CHAINS).filter((c) => c.enabled && !c.evm);
}

export function featuredChains(): ChainDefinition[] {
  return FEATURED_ORDER.map((k) => CHAINS[k]);
}

export function coreHoldingsChains(): ChainDefinition[] {
  return CORE_HOLDINGS_ORDER.map((k) => CHAINS[k]);
}

export function issuanceChains(): ChainDefinition[] {
  return ISSUANCE_ORDER.map((k) => CHAINS[k]);
}

const TESTNET_ORDER: Array<(typeof ChainKey)[keyof typeof ChainKey]> = [
  ChainKey.EthereumSepolia,
  ChainKey.AvalancheFuji,
  ChainKey.BaseSepolia,
  ChainKey.ArbSepolia,
  ChainKey.CardanoPreprod,
  ChainKey.NearTestnet,
  ChainKey.BnbTestnet,
  ChainKey.SolanaDevnet,
];

export function testnetChains(): ChainDefinition[] {
  return TESTNET_ORDER.map((k) => CHAINS[k]).filter((c) => c.enabled);
}
