export const launchErrorAbi = [
  { type: "error", name: "InvalidName", inputs: [] },
  { type: "error", name: "InvalidSymbol", inputs: [] },
  { type: "error", name: "DecimalsOutOfRange", inputs: [{ name: "got", type: "uint8" }] },
  { type: "error", name: "SupplyZero", inputs: [] },
  { type: "error", name: "SupplyOverflow", inputs: [] },
  { type: "error", name: "TaxTooHigh", inputs: [{ name: "bps", type: "uint16" }] },
  { type: "error", name: "RecipientZero", inputs: [] },
  { type: "error", name: "LockDurationInvalid", inputs: [{ name: "seconds_", type: "uint64" }] },
  { type: "error", name: "DexUnsupported", inputs: [{ name: "dex", type: "uint8" }] },
  { type: "error", name: "ChainDisabled", inputs: [{ name: "chain", type: "uint8" }] },
  { type: "error", name: "InsufficientNative", inputs: [{ name: "have", type: "uint256" }, { name: "need", type: "uint256" }] },
  { type: "error", name: "LockNotMature", inputs: [{ name: "unlockAt", type: "uint256" }] },
  { type: "error", name: "NotLockOwner", inputs: [] },
  { type: "error", name: "PeerAlreadySet", inputs: [{ name: "eid", type: "uint32" }] },
  { type: "error", name: "PeerNotSet", inputs: [{ name: "eid", type: "uint32" }] },
  { type: "error", name: "ModuleDisabled", inputs: [{ name: "flag", type: "uint8" }] },
  { type: "error", name: "OFTPathMustBeFeeFree", inputs: [] },
  { type: "error", name: "AlreadyInitialized", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "UnknownModule", inputs: [{ name: "flags", type: "uint16" }] },
  { type: "error", name: "InvalidSupplyMode", inputs: [{ name: "mode", type: "uint8" }] },
  { type: "error", name: "InvalidLockMode", inputs: [{ name: "mode", type: "uint8" }] },
  { type: "error", name: "InvalidOwnershipAction", inputs: [{ name: "action", type: "uint8" }] },
  { type: "error", name: "MintNotAllowed", inputs: [] },
  { type: "error", name: "InvalidPeer", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [{ name: "have", type: "uint256" }, { name: "need", type: "uint256" }] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "CloneFailed", inputs: [] },
  { type: "error", name: "InvalidChainKey", inputs: [{ name: "chain", type: "uint8" }] },
  { type: "error", name: "InvalidDexKind", inputs: [{ name: "dex", type: "uint8" }] },
  { type: "error", name: "InvalidLaunchStep", inputs: [{ name: "step", type: "uint8" }] },
  { type: "error", name: "InvalidLaunchStatus", inputs: [{ name: "status", type: "uint8" }] },
  { type: "error", name: "NotInitialized", inputs: [] },
  { type: "error", name: "EndpointZero", inputs: [] },
  { type: "error", name: "LengthMismatch", inputs: [] },
] as const;
