import { featuredChains } from "@ysk-mint/config";
import cmc from "./cmcCatalog.json";
import { nameLooksLikeUsEquity } from "./tokenizedEquity.ts";

export type TokenVm =
  | "evm"
  | "near"
  | "cardano"
  | "solana"
  | "tron"
  | "sui"
  | "ton"
  | "aptos"
  | "hypercore"
  | "bitcoin"
  | "xrpl"
  | "stellar"
  | "cosmos"
  | "starknet";

export type TokenRecord = {
  id: string;
  vm: TokenVm;
  chainId: number;
  symbol: string;
  name: string;
  decimals: number;
  address?: string;
  icon: string;
  native?: boolean;
};

const I = (file: string) => `/tokens/${file}.png`;

const NAT = (vm: TokenVm, chainId: number, id: string, symbol: string, name: string, decimals: number, icon: string): TokenRecord => ({
  id,
  vm,
  chainId,
  symbol,
  name,
  decimals,
  icon: I(icon),
  native: true,
});

/**
 * Native coins (always queried) plus CMC ∪ CoinGecko top-500 platform
 * contracts on featured chains. Regenerated by `pnpm snapshot:top500`.
 * Not the entire CMC/CG universe. Icons are local 64×64 copies.
 * EVM decimals from on-chain eth_call (CMC contractDecimals is often wrong).
 */
const NATIVES: TokenRecord[] = [
  NAT("evm", 1, "eth-native", "ETH", "Ethereum", 18, "eth"),
  NAT("evm", 8453, "base-native", "ETH", "Ethereum", 18, "eth"),
  NAT("evm", 42161, "arb-native", "ETH", "Ethereum", 18, "eth"),
  NAT("evm", 56, "bnb-native", "BNB", "BNB", 18, "bnb"),
  NAT("evm", 43114, "avax-native", "AVAX", "Avalanche", 18, "avax"),
  NAT("evm", 137, "pol-native", "POL", "Polygon", 18, "pol"),
  NAT("evm", 10, "op-native", "ETH", "Ethereum", 18, "eth"),
  NAT("evm", 250, "ftm-native", "FTM", "Fantom", 18, "ftm"),
  NAT("evm", 5000, "mnt-native", "MNT", "Mantle", 18, "mnt"),
  NAT("evm", 480, "world-native", "ETH", "Ethereum", 18, "eth"),
  NAT("evm", 999, "hype-native", "HYPE", "HYPE", 18, "hype"),
  NAT("near", 397, "near-native", "NEAR", "NEAR", 24, "near"),
  NAT("cardano", 1815, "ada-native", "ADA", "Cardano", 6, "ada"),
  NAT("solana", 101, "sol-native", "SOL", "Solana", 9, "sol"),
  NAT("tron", 728126428, "trx-native", "TRX", "TRON", 6, "trx"),
  NAT("sui", 784, "sui-native", "SUI", "Sui", 9, "sui"),
  NAT("ton", 607, "ton-native", "TON", "Toncoin", 9, "ton"),
  NAT("aptos", 637, "apt-native", "APT", "Aptos", 8, "apt"),
  NAT("hypercore", 998, "hypercore-native", "HYPE", "HYPE", 8, "hype"),
];

function nativeDecimals(vm: string, symbol: string) {
  if (symbol === "USD") return 6;
  if (vm === "near") return 24;
  if (vm === "cardano" || vm === "tron" || vm === "xrpl" || vm === "cosmos") return 6;
  if (vm === "stellar") return 7;
  if (vm === "bitcoin") return 8;
  if (vm === "solana" || vm === "sui" || vm === "ton") return 9;
  if (vm === "aptos" || vm === "hypercore") return 8;
  return 18;
}

function nativeIcon(symbol: string, chainId: number) {
  const s = symbol.toLowerCase();
  if (["eth", "bnb", "avax", "pol", "ftm", "mnt", "hype", "ada", "near", "sol", "trx", "sui", "ton", "apt", "op", "btc", "xrp", "xlm", "atom", "osmo", "tia", "strk", "fil"].includes(s))
    return s === "eth" ? "eth" : s;
  if (chainId === 10) return "op";
  if (chainId === 480) return "wld";
  return "eth";
}

const HAVE_NATIVE = new Set(NATIVES.map((t) => t.chainId));
const AUTO_NATIVES: TokenRecord[] = featuredChains()
  .filter((c) => !c.testnet && !HAVE_NATIVE.has(c.chainId))
  .map((c) =>
    NAT(
      c.vm as TokenVm,
      c.chainId,
      `${c.key}-${c.chainId}-native`,
      c.nativeSymbol,
      c.name,
      nativeDecimals(c.vm, c.nativeSymbol),
      nativeIcon(c.nativeSymbol, c.chainId),
    ),
  );

const EXTRA: TokenRecord[] = [
  { id: "eth-weth", vm: "evm", chainId: 1, symbol: "WETH", name: "Wrapped Ether", decimals: 18, address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", icon: I("eth") },
  { id: "eth-steth", vm: "evm", chainId: 1, symbol: "stETH", name: "Lido Staked ETH", decimals: 18, address: "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84", icon: I("steth") },
  { id: "eth-wsteth", vm: "evm", chainId: 1, symbol: "wstETH", name: "Wrapped stETH", decimals: 18, address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0", icon: I("wsteth") },
  { id: "eth-wbtc", vm: "evm", chainId: 1, symbol: "WBTC", name: "Wrapped Bitcoin", decimals: 8, address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599", icon: I("wbtc") },
  { id: "eth-cbbtc", vm: "evm", chainId: 1, symbol: "cbBTC", name: "Coinbase Wrapped BTC", decimals: 8, address: "0xcbb7C0000ab88B473b1f5aFd9ef808440eed33Bf", icon: I("cbbtc") },
  { id: "base-cbbtc", vm: "evm", chainId: 8453, symbol: "cbBTC", name: "Coinbase Wrapped BTC", decimals: 8, address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf", icon: I("cbbtc") },
  { id: "arb-cbbtc", vm: "evm", chainId: 42161, symbol: "cbBTC", name: "Coinbase Wrapped BTC", decimals: 8, address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf", icon: I("cbbtc") },
  { id: "base-wbtc", vm: "evm", chainId: 8453, symbol: "WBTC", name: "Wrapped Bitcoin", decimals: 8, address: "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c", icon: I("wbtc") },
  { id: "pol-usdc", vm: "evm", chainId: 137, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359", icon: I("usdc") },
  { id: "pol-usdt", vm: "evm", chainId: 137, symbol: "USDT", name: "Tether", decimals: 6, address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F", icon: I("usdt") },
  { id: "op-usdc", vm: "evm", chainId: 10, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85", icon: I("usdc") },
  { id: "op-usdt", vm: "evm", chainId: 10, symbol: "USDT", name: "Tether", decimals: 6, address: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58", icon: I("usdt") },
  { id: "op-op", vm: "evm", chainId: 10, symbol: "OP", name: "Optimism", decimals: 18, address: "0x4200000000000000000000000000000000000042", icon: I("op") },
  { id: "ftm-usdc", vm: "evm", chainId: 250, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0x04068DA6C83AFCFA0e13ba15A6696662335D5B75", icon: I("usdc") },
  { id: "mnt-usdt", vm: "evm", chainId: 5000, symbol: "USDT", name: "Tether", decimals: 6, address: "0x201EBa5CC46D216Ce6DC03F6a759e8E766e956aE", icon: I("usdt") },
  { id: "world-usdc", vm: "evm", chainId: 480, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0x79A02482A880bCE3F13e09Da970dC34db4CD24d1", icon: I("usdc") },
  { id: "world-wld", vm: "evm", chainId: 480, symbol: "WLD", name: "Worldcoin", decimals: 18, address: "0x2cFc85d8e48F8EAB294be644d9E25C3030863003", icon: I("wld") },
  { id: "trx-usdt", vm: "tron", chainId: 728126428, symbol: "USDT", name: "Tether", decimals: 6, address: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t", icon: I("usdt") },
  { id: "sui-usdc", vm: "sui", chainId: 784, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC", icon: I("usdc") },
  { id: "cmc-3408-324-usdce", vm: "evm", chainId: 324, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4", icon: I("usdc") },
  { id: "ton-usdt", vm: "ton", chainId: 607, symbol: "USDT", name: "Tether", decimals: 6, address: "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs", icon: I("usdt") },
  { id: "apt-usdc", vm: "aptos", chainId: 637, symbol: "USDC", name: "USD Coin", decimals: 6, address: "0xbae207659db88bea0cbead6da0ed00aac12edcdda169e591cd41c94180b46f3b", icon: I("usdc") },
  { id: "eth-susde", vm: "evm", chainId: 1, symbol: "sUSDe", name: "Staked USDe", decimals: 18, address: "0x9D39A5DE30e57443BfF2A8307A4256c8797A3497", icon: I("usdc") },
  { id: "eth-benji", vm: "evm", chainId: 1, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 18, address: "0x3DDc84940Ab509C11B20B76B466933f40b750dc9", icon: I("usdc") },
  { id: "pol-benji", vm: "evm", chainId: 137, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 18, address: "0x408A634B8a8f0dE729B48574a3a7Ec3fE820B00A", icon: I("usdc") },
  { id: "arb-benji", vm: "evm", chainId: 42161, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 18, address: "0xB9e4765BCE2609bC1949592059B17Ea72fEe6C6A", icon: I("usdc") },
  { id: "avax-benji", vm: "evm", chainId: 43114, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 18, address: "0xE08b4c1005603427420e64252a8b120cacE4D122", icon: I("usdc") },
  { id: "base-benji", vm: "evm", chainId: 8453, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 18, address: "0x60CfC2b186a4CF647486e42c42B11cC6D571d1E4", icon: I("usdc") },
  { id: "sol-benji", vm: "solana", chainId: 101, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 9, address: "5Tu84fKBpe9vfXeotjvfvWdWbAjy3hqsExvuHgFqFxA1", icon: I("usdc") },
  { id: "apt-benji", vm: "aptos", chainId: 637, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 8, address: "0x7b5e9cac3433e9202f28527f707c89e1e47b19de2c33e4db9521a63ad219b739", icon: I("usdc") },
  { id: "xlm-benji", vm: "stellar", chainId: 148, symbol: "BENJI", name: "Franklin OnChain U.S. Government Money Fund", decimals: 7, address: "BENJI-GD5J73EKK5IYL5XS3FBTHHX7CZIYRP7QXDL57XFWGC2WVYWT326OBXRP", icon: I("usdc") },
  { id: "eth-wtgxx", vm: "evm", chainId: 1, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 18, address: "0x1feCF3d9d4Fee7f2c02917A66028a48C6706c179", icon: I("usdc") },
  { id: "arb-wtgxx", vm: "evm", chainId: 42161, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 18, address: "0xfeb26f0943c3885b2cb85a9f933975356c81c33d", icon: I("usdc") },
  { id: "avax-wtgxx", vm: "evm", chainId: 43114, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 18, address: "0x870FD36B3bf7f5abeEEa2C8D4abdF1dc4E33109d", icon: I("usdc") },
  { id: "base-wtgxx", vm: "evm", chainId: 8453, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 18, address: "0x5096b85Ed11798fDdCB8b5CB27C399c04689c435", icon: I("usdc") },
  { id: "op-wtgxx", vm: "evm", chainId: 10, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 18, address: "0x870FD36B3bf7f5abeEEa2C8D4abdF1dc4E33109d", icon: I("usdc") },
  { id: "sol-wtgxx", vm: "solana", chainId: 101, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 9, address: "Em46fxxwgY2RRoUbBMSbEjJwY62x3ESMNdhnsGpEKewm", icon: I("usdc") },
  { id: "xlm-wtgxx", vm: "stellar", chainId: 148, symbol: "WTGXX", name: "WisdomTree Government Money Market Digital Fund", decimals: 7, address: "WTGXX-GDMBNMFJ3TRFLASJ6UGETFME3PJPNKPU24C7KFDBEBPQFG2CI6UC3JG6", icon: I("usdc") },
  { id: "eth-tbill", vm: "evm", chainId: 1, symbol: "TBILL", name: "OpenEden T-Bills", decimals: 6, address: "0xdd50C053C096CB04A3e3362E2b622529EC5f2e8a", icon: I("usdc") },
  { id: "arb-tbill", vm: "evm", chainId: 42161, symbol: "TBILL", name: "OpenEden T-Bills", decimals: 6, address: "0xF84D28A8D28292842dD73D1c5F99476A80b6666A", icon: I("usdc") },
  { id: "eth-usdm", vm: "evm", chainId: 1, symbol: "USDM", name: "Mountain Protocol USD", decimals: 18, address: "0x59D9356E565Ab3A36dD77763Fc0d87fEaf85508C", icon: I("usdc") },
  { id: "eth-bib01", vm: "evm", chainId: 1, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "base-bib01", vm: "evm", chainId: 8453, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "bsc-bib01", vm: "evm", chainId: 56, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "pol-bib01", vm: "evm", chainId: 137, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "arb-bib01", vm: "evm", chainId: 42161, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "gnosis-bib01", vm: "evm", chainId: 100, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "avax-bib01", vm: "evm", chainId: 43114, symbol: "bIB01", name: "Backed IB01 $ Treasury Bond 0-1yr", decimals: 18, address: "0xCA30c93B02514f86d5C86a6e375E3A330b435Fb5", icon: I("usdc") },
  { id: "eth-syrupusdc", vm: "evm", chainId: 1, symbol: "syrupUSDC", name: "Syrup USDC", decimals: 6, address: "0x80ac24aA929eaF5013f6436cdA2a7ba190f5Cc0b", icon: I("usdc") },
  { id: "eth-aaplx", vm: "evm", chainId: 1, symbol: "AAPLx", name: "Apple xStock", decimals: 18, address: "0x9d275685dC284C8eB1C79f6ABA7a63Dc75ec890a", icon: I("eth") },
  { id: "avax-btsla", vm: "evm", chainId: 43114, symbol: "bTSLA", name: "Backed Tesla", decimals: 18, address: "0x14A5f2872396802C3Cc8942A39Ab3E4118EE5038", icon: I("avax") },
  { id: "avax-bgoogl", vm: "evm", chainId: 43114, symbol: "bGOOGL", name: "Backed Alphabet Class A", decimals: 18, address: "0xebEe37aAf2905b7BDa7E3b928043862e982e8F32", icon: I("avax") },
  { id: "avax-bcoin", vm: "evm", chainId: 43114, symbol: "bCOIN", name: "Backed Coinbase Global", decimals: 18, address: "0xbbcb0356bB9e6B3faa5cbF9E5f36185d53403Ac9", icon: I("avax") },
  { id: "avax-bcspx", vm: "evm", chainId: 43114, symbol: "bCSPX", name: "Backed CSPX Core S&P 500", decimals: 18, address: "0x1e2C4fb7ede391d116E6B41cD0608260e8801d59", icon: I("avax") },
  { id: "base-aaplc", vm: "evm", chainId: 8453, symbol: "AAPLc", name: "Apple Coinbase Tokenized Stock", decimals: 18, address: "0xb200000000000000000000C2e324d24d7eEcd1fb", icon: I("eth") },
  { id: "base-nvdac", vm: "evm", chainId: 8453, symbol: "NVDAc", name: "NVIDIA Coinbase Tokenized Stock", decimals: 18, address: "0xb20000000000000000000078ee7ce2fE4908108C", icon: I("eth") },
  { id: "base-googlc", vm: "evm", chainId: 8453, symbol: "GOOGLc", name: "Alphabet Coinbase Tokenized Stock", decimals: 18, address: "0xb2000000000000000000002D0BA3164cc74f58B7", icon: I("eth") },
  { id: "base-metac", vm: "evm", chainId: 8453, symbol: "METAc", name: "Meta Coinbase Tokenized Stock", decimals: 18, address: "0xb2000000000000000000008bC8786B856E61707C", icon: I("eth") },
  { id: "base-amznc", vm: "evm", chainId: 8453, symbol: "AMZNc", name: "Amazon Coinbase Tokenized Stock", decimals: 18, address: "0xb200000000000000000000d9192b6B456483C2E8", icon: I("eth") },
  { id: "base-tslac", vm: "evm", chainId: 8453, symbol: "TSLAc", name: "Tesla Coinbase Tokenized Stock", decimals: 18, address: "0xb2000000000000000000001e800a7f5189430cD0", icon: I("eth") },
  { id: "base-msftc", vm: "evm", chainId: 8453, symbol: "MSFTc", name: "Microsoft Coinbase Tokenized Stock", decimals: 18, address: "0xB200000000000000000000Ab99cFa739E253872B", icon: I("eth") },
  { id: "base-coinc", vm: "evm", chainId: 8453, symbol: "COINc", name: "Coinbase Coinbase Tokenized Stock", decimals: 18, address: "0xb200000000000000000000c85a31389D71F3ecfb", icon: I("eth") },
];

const fromCmc = (cmc as TokenRecord[]).filter((t) => t.address);

/** Same CREATE2 xStock addresses as Ethereum; confirmed live on Optimism. */
function cloneEthXstocksToOp(list: TokenRecord[]): TokenRecord[] {
  const out: TokenRecord[] = [];
  for (const t of list) {
    if (t.vm !== "evm" || t.chainId !== 1 || !t.address) continue;
    if (!t.address.startsWith("0x") && !t.address.startsWith("0X")) continue;
    if (!nameLooksLikeUsEquity(t.symbol, t.name)) continue;
    if (!/xstock/i.test(`${t.symbol} ${t.name}`)) continue;
    out.push({ ...t, id: `${t.id}-op`, chainId: 10 });
  }
  return out;
}

function dedupeCatalog(list: TokenRecord[]) {
  const seen = new Set<string>();
  const out: TokenRecord[] = [];
  for (const t of list) {
    const k = t.address ? `${t.chainId}:${t.address.toLowerCase()}` : t.id;
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(t);
  }
  return out;
}

const SEEDED = [...EXTRA, ...fromCmc];
export const TOKEN_CATALOG: TokenRecord[] = dedupeCatalog([...NATIVES, ...AUTO_NATIVES, ...SEEDED, ...cloneEthXstocksToOp(SEEDED)]);

export function tokensFor(vm: TokenVm, chainId?: number) {
  return TOKEN_CATALOG.filter((t) => t.vm === vm && (chainId == null || t.chainId === chainId));
}

export function cardanoByUnit(unit: string) {
  const compact = unit.replace(".", "").toLowerCase();
  return TOKEN_CATALOG.find((t) => {
    if (t.vm !== "cardano" || !t.address) return false;
    const a = t.address.toLowerCase();
    return compact === a || compact.startsWith(a) || a.startsWith(compact);
  });
}

export function solByMint(mint: string) {
  return TOKEN_CATALOG.find((t) => t.vm === "solana" && t.address === mint);
}

export function catalogToken(chainId: number, address: string) {
  if (!address) return TOKEN_CATALOG.find((t) => t.chainId === chainId && t.native);
  const exact = TOKEN_CATALOG.find((t) => t.chainId === chainId && t.address === address);
  if (exact) return exact;
  const a = address.toLowerCase();
  return TOKEN_CATALOG.find((t) => t.chainId === chainId && t.address && t.address.toLowerCase() === a);
}
